import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Badge,
  Bell,
  BookOpen,
  Braces,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Compass,
  Copy,
  FileText,
  Filter,
  Gavel,
  Hand,
  Hash,
  HelpCircle,
  History,
  Info,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  List,
  Lock,
  Mail,
  Maximize,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  MicOff,
  MicVocal,
  Minus,
  MinusCircle,
  Monitor,
  MoreVertical,
  Music,
  PartyPopper,
  Pause,
  PauseCircle,
  Pencil,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  Receipt,
  RefreshCw,
  Rocket,
  Save,
  Search,
  SearchX,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShieldUser,
  SlidersHorizontal,
  SmilePlus,
  Split,
  Square,
  Star,
  Terminal,
  Ticket,
  Timer,
  Trash2,
  TrendingUp,
  Unlock,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  Webhook,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps the legacy Material-Symbols string names (still used throughout the app
 * as data-driven icon keys) to their Lucide equivalents. Lucide is the project's
 * canonical icon set — one visual language, SVG, themeable, no icon font.
 */
const iconMap: Record<string, LucideIcon> = {
  account_tree: Split,
  add: Plus,
  add_circle: PlusCircle,
  add_reaction: SmilePlus,
  admin_panel_settings: UserCog,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_upward: ArrowUp,
  badge: Badge,
  bolt: Zap,
  call_split: Split,
  cancel: XCircle,
  celebration: PartyPopper,
  chat: MessageSquare,
  check: Check,
  check_circle: CheckCircle,
  chevron_right: ChevronRight,
  circle: Circle,
  close: X,
  confirmation_number: Ticket,
  content_copy: Copy,
  dashboard: LayoutDashboard,
  dashboard_customize: LayoutGrid,
  data_object: Braces,
  delete: Trash2,
  delete_sweep: Trash2,
  description: FileText,
  deselect: Square,
  dns: Server,
  edit: Pencil,
  error: AlertCircle,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  explore: Compass,
  filter_alt: Filter,
  fit_screen: Maximize,
  forum: MessagesSquare,
  gavel: Gavel,
  hash: Hash,
  help: HelpCircle,
  history: History,
  info: Info,
  library_music: Music,
  lightbulb: Lightbulb,
  list: List,
  lock: Lock,
  lock_open: Unlock,
  mail: Mail,
  menu: Menu,
  menu_book: BookOpen,
  "message-circle": MessageCircle,
  mic: Mic,
  mic_off: MicOff,
  more_vert: MoreVertical,
  notifications: Bell,
  pause_circle: PauseCircle,
  person_add: UserPlus,
  person_remove: UserMinus,
  play_arrow: Play,
  play_circle: PlayCircle,
  receipt_long: Receipt,
  remove: Minus,
  remove_circle: MinusCircle,
  rocket: Rocket,
  rocket_launch: Rocket,
  save: Save,
  schedule: Clock,
  search: Search,
  search_off: SearchX,
  security: ShieldCheck,
  select_check_box: CheckSquare,
  send: Send,
  settings: Settings,
  settings_voice: MicVocal,
  shield: Shield,
  shield_person: ShieldUser,
  star: Star,
  sync: RefreshCw,
  task_alt: CheckCircle2,
  terminal: Terminal,
  timer: Timer,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  users: Users,
  viewport: Monitor,
  warning: AlertTriangle,
  waving_hand: Hand,
  webhook: Webhook,
  webhooks: Webhook,
  pause: Pause,
  activity: Activity,
};

interface IconProps {
  name: string;
  className?: string;
  /** Renders a solid (filled) glyph — used for active/selected states. */
  filled?: boolean;
  /** Pixel size. Defaults to 20 to match the previous icon baseline. */
  size?: number;
}

export function Icon({ name, className = "", filled = false, size = 20 }: IconProps) {
  const LucideGlyph = iconMap[name] ?? Circle;
  return (
    <LucideGlyph
      className={className}
      size={size}
      strokeWidth={1.5}
      fill={filled ? "currentColor" : "none"}
      aria-hidden="true"
    />
  );
}
