import type { Ticket } from "./types.js";

interface TranscriptMessage {
  author: string;
  authorId: string;
  avatarUrl: string | null;
  content: string;
  timestamp: Date;
  attachments: string[];
}

export function buildTranscriptHtml(
  ticket: Ticket,
  messages: TranscriptMessage[],
  guildName: string,
): string {
  const escapedMessages = messages.map((m) => ({
    ...m,
    content: escapeHtml(m.content),
    author: escapeHtml(m.author),
  }));

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ticket #${ticket.id} Transcript</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; background: #1a1a2e; color: #e0e0e0; padding: 20px; }
    .header { background: #16213e; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
    .header h1 { color: #a3a6ff; font-size: 1.5rem; }
    .header .meta { color: #888; font-size: 0.875rem; margin-top: 8px; }
    .message { display: flex; gap: 12px; padding: 8px 16px; }
    .message:hover { background: rgba(255,255,255,0.02); }
    .avatar { width: 40px; height: 40px; border-radius: 50%; background: #333; flex-shrink: 0; }
    .content { flex: 1; }
    .author { font-weight: 600; color: #a3a6ff; font-size: 0.875rem; }
    .timestamp { color: #666; font-size: 0.75rem; margin-left: 8px; }
    .text { margin-top: 4px; line-height: 1.5; word-wrap: break-word; }
    .attachment { color: #7289da; text-decoration: underline; font-size: 0.875rem; }
    .footer { text-align: center; color: #666; font-size: 0.75rem; margin-top: 20px; padding-top: 20px; border-top: 1px solid #333; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Ticket #${ticket.id} -- ${escapeHtml(ticket.categoryName ?? "General")}</h1>
    <div class="meta">
      <p>Guild: ${escapeHtml(guildName)} | Created by: ${ticket.userId} | Status: ${ticket.status}</p>
      <p>Created: ${ticket.createdAt.toISOString()}${ticket.closedAt ? ` | Closed: ${ticket.closedAt.toISOString()}` : ""}</p>
      ${ticket.closeReason ? `<p>Close reason: ${escapeHtml(ticket.closeReason)}</p>` : ""}
    </div>
  </div>

  ${escapedMessages
    .map(
      (m) => `
  <div class="message">
    ${m.avatarUrl ? `<img class="avatar" src="${escapeHtml(m.avatarUrl)}" alt="">` : '<div class="avatar"></div>'}
    <div class="content">
      <span class="author">${m.author}</span>
      <span class="timestamp">${m.timestamp.toISOString()}</span>
      <div class="text">${m.content}</div>
      ${m.attachments.map((a) => `<a class="attachment" href="${escapeHtml(a)}">${escapeHtml(a)}</a>`).join("<br>")}
    </div>
  </div>`,
    )
    .join("\n")}

  <div class="footer">
    <p>Transcript generated by FluxCore | ${messages.length} messages</p>
  </div>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
